name: Deploy to Firebase Hosting on Pull request
'on': pull_request
jobs:
    build_and_preview:
        if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
            - name: Install node v16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: www/package-lock.json
            - name: Install latest Chrome version
              uses: browser-actions/setup-chrome@latest
            - name: Install Rust toolchain
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - name: Cache Crates
              uses: actions/cache@v3
              with:
                  path: |
                      target
                      ~/.cargo
                  key: cache-${{ runner.os }}-crates-
            - name: Test Rust code
              run: wasm-pack test --chrome --headless
            - name: Compile Rust code to WebAssembly
              run: wasm-pack build
            - name: Build the app
              working-directory: ./www
              run: |
                  npm ci
                  npm run build
            - name: Deploy app to temporary URL
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAME_OF_LIFE_9A203 }}'
                  projectId: game-of-life-9a203
                  expires: 1d
